# expectation is we have artificat in a run 

name: 12-01-release
on: workflow_dispatch
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: checkout 
            uses: actions/checkout@v4
          - name: setup java 
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin' # See 'Supported distributions' for available options
              java-version: '21'
          - name: buid 
            run: mvn install
          - name: artifact-upload
            uses: actions/upload-artifact@v4
            with:
              name: todo-artifact
              path: target/
    
    release:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Download web-app content
          uses: actions/download-artifact@v4
          with:
            name: todo-artifact
            path: target/
               
        - name: Archive site content
          uses: thedoctor0/zip-release@master
          with:
            filename: site.zip
            
        - name: Create GitHub release
          id: create-new-release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.run_number }}
            release_name: Release ${{ github.run_number }}
            
        - name: Upload release asset
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create-new-release.outputs.upload_url }}
            asset_path: ./site.zip
            asset_name: site-v${{ github.run_number }}.zip
            asset_content_type: application/zip
